[package]
name = 'kime-web'
version = '0.1.0'
authors = ['Xnuk Shuman <xnuk+kime@xnu.kr>']
edition = '2021'
license = 'GPL-3.0-or-later'
rust-version = '1.78.0'

[lib]
crate-type = ['cdylib']

[dependencies]
serde_yaml = '0.8.26'
gloo-events = '0.2.0'

[dependencies.serde]
version = '1.0.203'
features = ['derive']

[dependencies.kime-engine-core]
git = 'https://github.com/xnuk/kime'
tag = 'v4.0.0-pre.1'
default-features = false
features = []

[dependencies.kime-engine-backend]
git = 'https://github.com/xnuk/kime'
tag = 'v4.0.0-pre.1'

[dependencies.kime-engine-backend-hangul]
git = 'https://github.com/xnuk/kime'
tag = 'v4.0.0-pre.1'

[dependencies.web-sys]
version = '0.3.69'
features = [
    'KeyboardEvent',
    'HtmlElement',
    'console',
    'CustomEventInit',
    'CustomEvent',
]

[dependencies.js-sys]
version = '0.3.69'

[dependencies.wasm-bindgen]
version = '0.2.92'
default-features = false
features = []
