# # cannot generate lockfile for now
# [settings]
# experimental = true
# lockfile = true

[tools]
'github:WebAssembly/binaryen' = 'version_131'
'github:wasm-bindgen/wasm-bindgen' = '0.2.127'
bun = '1.2.22'

[tasks.build]
run = 'bun i && bun run build'

[tasks.dev]
run = 'bun i && bun run dev'
