name: build
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    # Use mise
    - uses: jdx/mise-action@v2

    # Setup Rust environment & test codes
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - run: cargo fmt -- --check
    - run: cargo clippy --no-deps -- -D warnings
    - run: cargo test

    - run: mise run build

    - uses: actions/upload-pages-artifact@v4
      with:
        path: dist/web/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
