name: build
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2

    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm

    - run: |
        mkdir -p ~/.local/bin
        cd ~/.local/bin

        curl https://zyedidia.github.io/eget.sh | sh

        ./eget xnuk/swc-minifier --tag=0.2.3
        ./eget WebAssembly/binaryen --tag=version_117 --file=wasm-opt
        ./eget rustwasm/wasm-bindgen --tag=0.2.92

        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - run: pnpm install
    - run: pnpm build

    - run: >
        swc-minifier --config=swc-minifier.json dist/web/index.js > dist/web/index.min.js &&
        mv dist/web/index.min.js dist/web/index.js

    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist/web/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
